---
- name: FirewallD rules
  firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  with_items:
    - ssh
    - http
    - https
- name: FirewallD rules( ports )
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{ item }}"
    state: enabled
  with_items:
    - 6443/tcp
    - 8472/udp
    - 10250/tcp
- firewalld:
    source: "{{ item }}"
    zone: trusted
    immediate: yes
    permanent: true
    state: enabled
  with_items:
    - 10.42.0.0/16
    - 10.43.0.0/16